spring.application.name=JobPortal
spring.datasource.url=jdbc:postgresql://localhost:5432/jobPortal_db
spring.datasource.username=postgres
spring.datasource.password=6969
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

# dev server port
server.port=8099
